@baseUrl = http://localhost:3333
@authToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTRiZmRlMy01MDE3LTQyNDktOWFlYS1iODZkMTRiMjcwZGEiLCJpYXQiOjE3Nzc5MDQzNzB9.dJYgRWr0GlRDQdAaYyv4WF-ad-TmoCDRaUQbByCpfdxo9fn5kpSrqxQkL2kivYIjRdpntLREFX-MvsjmSCJN_yHKQjHiMdNmGHBuF0lNyvAONnFj2cqfWLQSUV6MvZFOYq7eYCetDzuOSBHT7a6lQ-bE05IfICPbS5Ai2YTgEP4vz3pTxSM_OMRjCxqoEOQVQ81Z0Rkv8yKaYi9CYVcdQdRbegX_sloJNyG66YCJwgL4JLhvRpTuvtwJG3vHix8z8O2D5xj7KgkcCB3UnZl8FuAgeU1SR2Nwkd75nbSnhdRozLzjnFzjiBResxd1pKf9njsfHqcKLOsH--8uQY3cbg

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Marcos Valentini",
    "email": "marcos@gmail.com",
    "password": "12345678"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "marcos@gmail.com",
    "password": "12345678"
}

###

# @name create_note
POST {{baseUrl}}/notes
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Título",
    "content": "Content",
    "type": "MATCH"

}