@baseUrl = http://localhost:3333
@authToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNjJlNzM2Yy0yZjczLTQxNjUtOTk4Yi0wZDA2MzRlNzRlNmUiLCJpYXQiOjE3NzczMDgyMzB9.DNcawqPo2NJOrY-OL5obCX485ar1pGUQSz4gGHjfVsHFbAc2SjSDxWxmrvhbVDSBQPRWw7jTtsrYUZZBJJyGN8GSEq47dkM41dO3kckES1V0G0ITle6YKdIa8Xjlv4zAwS4QfkPaaNXnwpE4TAxC5QTPkavBWFYyRZH5eCfJekOTGWdi-9G0gWbg74DWeR7jDv3dQnT0eZcDqEIpoxNvCuXBBh7dYcZ5Khrv3_fzr-jhVq98g3vMCGGM2Uc9SpbSmqVPFxubCN22ikNb6zcU5t0L0Fr7CmK4dmJzy7z5t5oGvudosRqf6aljgDFDs9DmUzp3QHW0ji6-z6XBEexvFA

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Marcos Valentini",
    "email": "marcos@gmail.com",
    "password": "12345678"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "marcos@gmail.com",
    "password": "12345678"
}

###

# @name create_subjects
POST {{baseUrl}}/subjects
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "NestJS"
}